# Generated by Django 3.0.2 on 2020-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.SlugField()),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('usertype', models.IntegerField()),
            ],
        ),
    ]
