# Generated by Django 3.0.2 on 2020-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200129_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(default='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(default=3),
        ),
    ]
